### PR TITLE
Switch zipcode coordinates order to lng,lat

### PR DESCRIPTION
**Pull request by stuartsan**
Was previously `[lat,lng]` for easier consumption by mapbox.js/leaflet but `[lng, lat]` is the more standard way to go and this makes it easier for the updated map code to consume.

### CODE REVIEW

**Comment by shazow** [comment]
Any citation for `lng, lat` being more standard? Every example I can find is `lat, lng`. (The diff itself looks fine otherwise.)

**Comment by stuartsan** [comment]
@shazow , I learned this from mapbox gl's [docs](https://www.mapbox.com/help/mapbox-gl-js-fundamentals/#coordinates):

> Where Mapbox GL JS handles coordinates as arrays (here [-74.50, 40]), it assumes that the coordinates are in longitude, latitude order (vs latitude, longitude in Leaflet and Mapbox.js). This order corresponds to the order of coordinates in GeoJSON and every other geospatial format, as well as math’s X, Y ordering.

**Review by shazow — APPROVED** [review]
TIL about [lon,lat] being more standard these days. Looks good!

**Comment by stuartsan** [comment]
Thanks @shazow! Gonna merge this.

**Pull request merged**
