### PR TITLE
Switch to yarn. Fixes #53

### LINKED ISSUE #53: Switch to yarn
And use a yarn.lock

### PR DESCRIPTION
**Pull request by ryanhobsonsmith**

### CODE REVIEW

**Comment by stuartsan** [comment]
Should we update the README as well?

**Comment by ryanhobsonsmith** [comment]
Good catch @stuartsan. Updated.

**Review by stuartsan — APPROVED** [review]
Thankyou!

**Comment by shazow** [comment]
:+1: gonna base my stuff off this branch. :)

**Comment by stuartsan** [comment]
I'm gonna merge this one as I'd like to start using it ASAP too, and it is straight forward.

**Pull request merged**
